### ISSUE TITLE
Dependencies not getting installed

### ISSUE THREAD

**Issue by NoelJacob** [mov-cli/mov-cli#23]
```
pip install git+https://github.com/mov-cli/mov-cli.git --verbose
```
```
Using pip 22.1.2 from /home/noel/.local/lib/python3.10/site-packages/pip (python 3.10)
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/mov-cli/mov-cli.git
  Cloning https://github.com/mov-cli/mov-cli.git to /tmp/pip-req-build-hcv4qijb
  Running command git version
  git version 2.37.1
  Running command git clone --filter=blob:none https://github.com/mov-cli/mov-cli.git /tmp/pip-req-build-hcv4qijb
  Cloning into '/tmp/pip-req-build-hcv4qijb'...
  Running command git rev-parse HEAD
  86278552635c8809f43ea73e275932d6ae25a65d
  Resolved https://github.com/mov-cli/mov-cli.git to commit 86278552635c8809f43ea73e275932d6ae25a65d
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/tmp/pip-req-build-hcv4qijb/setup.py", line 2, in <module>
      from mov_cli.__version__ import __core__
    File "/tmp/pip-req-build-hcv4qijb/mov_cli/__init__.py", line 1, in <module>
      from . import __main__
    File "/tmp/pip-req-build-hcv4qijb/mov_cli/__main__.py", line 7, in <module>
      from .websites.theflix import Theflix
    File "/tmp/pip-req-build-hcv4qijb/mov_cli/websites/theflix.py", line 5, in <module>
      import httpx
  ModuleNotFoundError: No module named 'httpx'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/tmp/pip-req-build-hcv4qijb/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-mm0mwpc9
  cwd: /tmp/pip-req-build-hcv4qijb/
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
I had to install bs4, colorama, and httpx manually and then run pip install to get it installed

**Comment by Poseidon444** [comment]
I will look into it

**Comment by Poseidon444** [comment]
Should be fixed now

**Comment by NoelJacob** [comment]
Nope I still get the same error. I tried #24 still the error.

**Comment by Poseidon444** [comment]
Should be fixed for sure now

**Comment by NoelJacob** [comment]
All good 🥳
