### ISSUE TITLE
[BUG] streamblasters: list index out of range; can't fetch the title from search result

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#93]
**Describe the bug**
The search result works well but while requesting the title from the search result, the app executes an error.

**Expected behavior**

**Screenshots**
Nil

**Error**
````
The name of the provider [actvid]: streamblasters
None
[!] Please Enter the name of the Movie: thunivu
https://streamblasters.art/?s=thunivu
[1] Thunivu (2023) Tamil MOVIE

[q] Exit!

[s] Search Again!

[d] Download!

[p] Switch Provider!

[sd] Download Whole Show!

Enter your choice: 1
https://streamblasters.art/movies/thunivu-2023-tamil/
[!] An error has occurred |  list index out of range
````

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Nil

**Possible cause**
Nil

**Possible solution**
Nil

**Version**
0.6.0

**Comment by ghost** [comment]
I know i am working on a fix

**Comment by ghost** [comment]
For some reason some return this
```{"embed_url":"<iframe width=\"720\" height=\"304\" src=\"https:\/\/dood.re\/e\/faoi37d5c63785y70eh5o794mk7frvqq\" scrolling=\"no\" frameborder=\"0\" allowfullscreen=\"true\"><\/iframe>","type":"dtshcode"}```

and some this

```{"embed_url":"https:\/\/dood.wf\/e\/b3vuro2m0j22je5si06ib82o350hg2l9","type":"iframe"}```

**Comment by bachig26** [comment]
> For some reason some return this `{"embed_url":"<iframe width=\"720\" height=\"304\" src=\"https:\/\/dood.re\/e\/faoi37d5c63785y70eh5o794mk7frvqq\" scrolling=\"no\" frameborder=\"0\" allowfullscreen=\"true\"><\/iframe>","type":"dtshcode"}`
> 
> and some this
> 
> `{"embed_url":"https:\/\/dood.wf\/e\/b3vuro2m0j22je5si06ib82o350hg2l9","type":"iframe"}`

I don't what this couldn't be, but I think this might related to some like the program have problem getting the correct resolution maybe they have different resolutions for some contents. I'm not sure, I maybe completely wrong.

**Comment by ghost** [comment]
fixed

**Comment by bachig26** [comment]
> fixed

~~still having the issue.~~ sorry, i was just looking for this 2 titles now, so I didn't check others. dood is fetching the video which has content in dood.

````
The name of the provider [actvid]: streamblasters
None
[!] Please Enter the name of the Movie: thunivu
https://streamblasters.art/?s=thunivu
[1] Thunivu (2023) Tamil MOVIE

[q] Exit!

[s] Search Again!

[d] Download!

[p] Switch Provider!

[sd] Download Whole Show!

Enter your choice: 1
https://streamblasters.art/movies/thunivu-2023-tamil/
https://dood.re/e/fqcbjyvy43ennpkvdarvaq5g7x8ejrl6
https://dood.re/e/fqcbjyvy43ennpkvdarvaq5g7x8ejrl6
https://dood.re/e/4x9edroehs9h3tg2xktcgxmjlbr01fv
[!] An error has occurred |  list index out of range
````
````
The name of the provider [actvid]: streamblasters
None
[!] Please Enter the name of the Movie: varisu
[1] Varisu (2023) Tamil MOVIE

[2] Varisu (2023) Tamil Audio launch HQ HDTV MOVIE

[q] Exit!

[s] Search Again!

[d] Download!

[p] Switch Provider!

[sd] Download Whole Show!

Enter your choice: 1
https://streamblasters.art/movies/varisu-2023-tamil/
https://dood.re/e/8vaymo7l9m11b3bf76qzbsjcem62s79u
https://dood.re/e/8vaymo7l9m11b3bf76qzbsjcem62s79u
https://dood.re/e/a7xrjcl1y1q3c71td7us2jvtchn4gim
[!] An error has occurred |  list index out of range
````

**Comment by bachig26** [comment]
@R3tr0Ananas i just found out, that the video is not available for that both content in dood. if possible, can also add the stream sb server along the doodstream to streamblasters?
